### ISSUE TITLE
Build Analyzer crash in ConsumptionTable

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1291]
Page crashes ("Error happened")

![image](https://user-images.githubusercontent.com/38327916/222538046-505841fe-8fd4-4a9a-a78c-31ab5ed7e306.png)

http://localhost:5800/analyzer?weapon=10&build2=LDE%2CRES%2CSRU%2CQSJ%2CISS%2CISS%2CISS%2CISS%2CISS%2CBRU%2CBRU%2CSSU&lde=6&effect=LDE&focused=1

```
Mar 2 09:53:16 PM  GET /analyzer?weapon=10&build2=LDE%2CRES%2CSRU%2CQSJ%2CISS%2CISS%2CISS%2CISS%2CISS%2CBRU%2CBRU%2CSSU&lde=6&effect=LDE&focused=1 500 - - 39.087 ms
Mar 2 09:53:16 PM  GET /analyzer?weapon=1011&build=SSU,SCU,SS,SCU,NS,SSU,SSU,SSU,SJ,RES,SRU,QSJ&build2=U,U,U,U,U,U,U,U,U,U,U,U&lde=0&focused=1 200 - - 38.268 ms
Mar 2 09:53:16 PM      at Array.map (<anonymous>)
Mar 2 09:53:16 PM      at ConsumptionTable (/opt/render/project/src/build/index.js:19199:114)
Mar 2 09:53:16 PM      at Uc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
Mar 2 09:53:16 PM      at Xc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
Mar 2 09:53:16 PM      at Z (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
Mar 2 09:53:16 PM      at Yc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
Mar 2 09:53:16 PM      at $c (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:80:140)
Mar 2 09:53:16 PM      at Z (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:345)
Mar 2 09:53:16 PM      at Yc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
Mar 2 09:53:16 PM  TypeError: Cannot read properties of undefined (reading 'value')
Mar 2 09:53:16 PM      at /opt/render/project/src/build/index.js:19209:213
Mar 2 09:53:16 PM      at Array.map (<anonymous>)
Mar 2 09:53:16 PM      at ConsumptionTable (/opt/render/project/src/build/index.js:19199:114)
Mar 2 09:53:16 PM      at Uc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
Mar 2 09:53:16 PM      at Xc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
Mar 2 09:53:16 PM      at Z (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
Mar 2 09:53:16 PM      at Yc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
Mar 2 09:53:16 PM      at $c (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:80:140)
Mar 2 09:53:16 PM      at Z (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:345)
Mar 2 09:53:16 PM      at Yc (/opt/render/project/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
```

**Comment by ElementUser** [comment]
Found the issue: the URL is missing the `build` attribute and it only has a `build2` attribute

From the URL mentioned (http://localhost:5800/analyzer?weapon=10&build2=LDE%2CRES%2CSRU%2CQSJ%2CISS%2CISS%2CISS%2CISS%2CISS%2CBRU%2CBRU%2CSSU&lde=6&effect=LDE&focused=1), basically all I did was replace `build2` with `build` and the URL works (though the second build doesn't have anything obviously)

The page loads just fine if it only contains a `build` attribute, but if it only contains a `build2` attribute, then you get the crash.

@Sendouc do you have any idea how you got the URL to *only* contain a `build2` attribute in the first place? From regular usage, I wasn't able to replicate getting the bugged URL with just a `build2` attribute

**Comment by Sendouc** [comment]
It could be that the user removed it there manually. I don't know how it could get there otherwise. Anyway it should not crash the site so maybe the fix is just to ignore it if `build` is missing.
