### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#330]
Currently most of the tests fail. The error is:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.plusStatus.findMany()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("0A000"), message: "cached plan must not change result type", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("plancache.c"), line: Some(718), routine: Some("RevalidateCachedQuery") }) }) })
    at cb (/Users/sendou/Documents/Programming/sendou-ink/node_modules/@prisma/client/runtime/index.js:34778:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ProcedureWithoutInput.call (/Users/sendou/Documents/Programming/sendou-ink/node_modules/@trpc/server/dist/router-830db415.cjs.dev.js:59:20) {
  clientVersion: '2.19.0'
}
```

With some Googling could be related to the new way of seeding the DB between tests:

```
beforeEach(() => {
  // TODO: use database transactions, instead of dropping and recreating the database with each individual test
  cy.exec("npm run migrate:reset -- --force");
});
```

Probably tests are otherwise broken too but this is the big problem to figure out for now.

**Comment by rofreg** [comment]
Yup, it looks like dropping and recreating the DB between tests makes the server's Postgres connection upset. I'll look into switching back to `npm run seed` for Cypress.
