### ISSUE TITLE
TypeError: next is not a function (passport.js)

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#770]
```
Mar 2 05:23:40 PM  /opt/render/project/src/node_modules/passport/lib/middleware/authenticate.js:364
Mar 2 05:23:40 PM          next(err);
Mar 2 05:23:40 PM          ^
Mar 2 05:23:40 PM  
Mar 2 05:23:40 PM  TypeError: next is not a function    at Strategy.strategy.error (/opt/render/project/src/node_modules/passport/lib/middleware/authenticate.js:364:9)    at /opt/render/project/src/node_modules/passport-oauth2/lib/strategy.js:177:34    at /opt/render/project/src/node_modules/oauth/lib/oauth2.js:191:18    at passBackControl (/opt/render/project/src/node_modules/oauth/lib/oauth2.js:132:9)    at IncomingMessage.<anonymous> (/opt/render/project/src/node_modules/oauth/lib/oauth2.js:157:7)    at IncomingMessage.emit (node:events:532:35)    at endReadableNT (node:internal/streams/readable:1346:12)    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Sendouc** [comment]
Probably fixed
