### ISSUE TITLE
Adding badge winners not working (Safari only?)

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#885]
```
Aug 21 10:49:36 AM  ZodError: [
Aug 21 10:49:36 AM    {
Aug 21 10:49:36 AM      "code": "invalid_union",
Aug 21 10:49:36 AM      "unionErrors": [
Aug 21 10:49:36 AM        {
Aug 21 10:49:36 AM          "issues": [
Aug 21 10:49:36 AM            {
Aug 21 10:49:36 AM              "code": "invalid_literal",
Aug 21 10:49:36 AM              "expected": "MANAGERS",
Aug 21 10:49:36 AM              "path": [
Aug 21 10:49:36 AM                "_action"
Aug 21 10:49:36 AM              ],
Aug 21 10:49:36 AM              "message": "Invalid literal value, expected \"MANAGERS\""
Aug 21 10:49:36 AM            },
Aug 21 10:49:36 AM            {
Aug 21 10:49:36 AM              "code": "invalid_type",
Aug 21 10:49:36 AM              "expected": "array",
Aug 21 10:49:36 AM              "received": "undefined",
Aug 21 10:49:36 AM              "path": [
Aug 21 10:49:36 AM                "managerIds"
Aug 21 10:49:36 AM              ],
Aug 21 10:49:36 AM              "message": "Required"
Aug 21 10:49:36 AM            }
Aug 21 10:49:36 AM          ],
Aug 21 10:49:36 AM          "name": "ZodError"
Aug 21 10:49:36 AM        },
Aug 21 10:49:36 AM        {
Aug 21 10:49:36 AM          "issues": [
Aug 21 10:49:36 AM            {
Aug 21 10:49:36 AM              "code": "invalid_literal",
Aug 21 10:49:36 AM              "expected": "OWNERS",
Aug 21 10:49:36 AM              "path": [
Aug 21 10:49:36 AM                "_action"
Aug 21 10:49:36 AM              ],
Aug 21 10:49:36 AM              "message": "Invalid literal value, expected \"OWNERS\""
Aug 21 10:49:36 AM            }
Aug 21 10:49:36 AM          ],
Aug 21 10:49:36 AM          "name": "ZodError"
Aug 21 10:49:36 AM        }
Aug 21 10:49:36 AM      ],
Aug 21 10:49:36 AM      "path": [],
Aug 21 10:49:36 AM      "message": "Invalid input"
Aug 21 10:49:36 AM    }
Aug 21 10:49:36 AM  ]
Aug 21 10:49:36 AM      at handleResult (/opt/render/project/src/node_modules/zod/lib/types.js:28:23)
Aug 21 10:49:36 AM      at ZodUnion.safeParse (/opt/render/project/src/node_modules/zod/lib/types.js:139:16)
Aug 21 10:49:36 AM      at ZodUnion.parse (/opt/render/project/src/node_modules/zod/lib/types.js:119:29)
Aug 21 10:49:36 AM      at parseRequestFormData (/opt/render/project/src/build/index.js:2574:19)
Aug 21 10:49:36 AM      at runMicrotasks (<anonymous>)
Aug 21 10:49:36 AM      at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 21 10:49:36 AM      at action5 (/opt/render/project/src/build/index.js:4604:14)
Aug 21 10:49:36 AM      at Object.callRouteAction (/opt/render/project/src/node_modules/@remix-run/server-runtime/dist/data.js:40:14)
Aug 21 10:49:36 AM      at handleDataRequest (/opt/render/project/src/node_modules/@remix-run/server-runtime/dist/server.js:94:18)
Aug 21 10:49:36 AM      at requestHandler (/opt/render/project/src/node_modules/@remix-run/server-runtime/dist/server.js:34:18) {
Aug 21 10:49:36 AM    issues: [
Aug 21 10:49:36 AM      {
Aug 21 10:49:36 AM        code: 'invalid_union',
Aug 21 10:49:36 AM        unionErrors: [Array],
Aug 21 10:49:36 AM        path: [],
Aug 21 10:49:36 AM        message: 'Invalid input'
Aug 21 10:49:36 AM      }
Aug 21 10:49:36 AM    ],
Aug 21 10:49:36 AM    addIssue: [Function (anonymous)],
Aug 21 10:49:36 AM    addIssues: [Function (anonymous)]
Aug 21 10:49:36 AM  }
```

**Comment by Sendouc** [comment]
Nobody reported any problems so likely working well enough.
